### ISSUE TITLE
v60 compatibility + Some labels disappear when Maneater Spawn.

### ISSUE THREAD

**Issue by AJAL8000** [Danny-vD/Mods-LethalCompany-MonitorLabels#11]
[Maneater](https://lethal-company.fandom.com/wiki/Maneater) need a tag.
Also, sometimes labels disappear randomly. Sometimes from all enemies, sometimes from a few, sometimes even from allies.

Also, I would recommend deprecating the mod if you're not going to be working on it anymore. :(

**Comment by AJAL8000** [comment]
It seems to consistently happen when Maneater spawn. Maybe that's where the problem comes from.

**Comment by Danny-vD** [comment]
Apologies, it took a while.
I was taking a break from the game.

**Comment by AJAL8000** [comment]
> Apologies, it took a while.
> I was taking a break from the game.

Thank you so much!
