### ISSUE TITLE
[1.3.0] Breaks with MoreCompany

### ISSUE THREAD

**Issue by throwitaway99** [Danny-vD/Mods-LethalCompany-MonitorLabels#3]
On the latest version (1.3.0), I do not see any labels when running the mod with MoreCompany. In order to reproduce, run only MonitorLabels and MoreCompany together. Go into Online, host a game, and watch as the player has no label on the map. Upon downgrading to 1.2.0, the issue is no longer present.

**Comment by Danny-vD** [comment]
That is very strange, since I didn't change anything that would affect MoreCompany, even more so since you said it worked fine in version 1.2.x

I'll look into it.

**Comment by Danny-vD** [comment]
Spend all day diagnosing this, and I finally found the issue.
It is fixed in the next update.
