### ISSUE TITLE
Can't disable monster and loot labels

### ISSUE THREAD

**Issue by Outclass0026** [Danny-vD/Mods-LethalCompany-MonitorLabels#4]
Hi,
Modifying the MonitorLabels.Utils.ConfigUtil file and settings labels for monsters and loot to false doesn't work.
So there is no possibility to see only the players label.

**Comment by Danny-vD** [comment]
Thanks for pointing this out, turns out I actually completely forgot to check the config when adding a label to enemies, and this will be fixed in the next update.

I was, however, not able to reproduce this for scrap, could it be you set it to false in the config and then forgot to save it?

**Comment by Outclass0026** [comment]
Hello,
Sorry for the delay, I did verify my config for the scrap and I confirm I configured showLabelOnScrap on false.
The only other parameter that I modified for scram is hideScrapLabelOnShip that I set to false too.

**Comment by Danny-vD** [comment]
I tested both as host and client with the same settings as you and I still cannot reproduce this error.

I don't understand why it might not work for you, but maybe if you delete the config file and let it regenerate by launching the game again it will work (not really an solution, I know).

I'm sorry I cannot be any more helpful.

Example of there not being any scrap labels:
![image](https://github.com/Danny-vD/Mods-LethalCompany-MonitorLabels/assets/39087133/13adba34-54e8-4219-93c9-844978ccc58a)

**Comment by Outclass0026** [comment]
I will try this, thanks for the support!
