### ISSUE TITLE
can we add keys(and other misc items) to the map?

### ISSUE THREAD

**Issue by bmatusiak** [Danny-vD/Mods-LethalCompany-MonitorLabels#5]
just tossing this out there..

can we add keys(and other misc items) to the map?

i know items show up as yellow,,   would be cool if it could show up as a yellow dot (instead of triangle) or something..

other misc items include  shotgun shells, and any items bought from the terminal

**Comment by Danny-vD** [comment]
Sorry for the late reply, I didn't want to promise anything before I looked into how I'd actually do it.
(And I was busy as well)

You'll be happy to hear this will be added in the next update, which will release soon (either today or tomorrow).

**Comment by bmatusiak** [comment]
cool i will test it out
